### ISSUE TITLE
Support Android and iOS？

### ISSUE THREAD

**Issue by AnkoGo123** [FyroxEngine/Fyrox#175]
**I believe that if you support Android and ios, there will be a large number of people starting this engine**

**Comment by mrDIMAS** [comment]
It is planned, but not for this year unfortunately. There is still lots of other stuff that has to be done.

**Comment by DuckEater54** [comment]
#### Would java interoperability be out of the question for this enhancement?
I'm semi-recent to rust but I'm decent with Java GUI development and have played with the graphics library. As of right now there aren't any crates that are decent for Android app development so temporary java interoperability with documentation for the graphics will be the quickest bet for this. I will be quite busy so I won't contribute often.

**Comment by weekendkoder** [comment]
Now we a heading to the next year 2023. In sept. 2022 its one year ago. Do you have any news on this request ? Will it be possible to the end of this year ? Or is this a plan for 2023 ?

**Comment by cad1994** [comment]
Same question!

**Comment by EvoTeamDevelop** [comment]
Sorry for duplicate question @mrDIMAS , but maybe there is some roadmap where it possible to see the plans?

**Comment by mrDIMAS** [comment]
Android support is planned for the beginning of this year. I want to experiment with this right after the release of 0.29 (should happen 8th of January). It is not an easy task, just because it requires a separate renderer (standard renderer is way too heavy for mobile). As for iOS support - I don't have any devices that can be used for testing, so I can't add it (unless there's a ways of doing this without a device, please let me know).

**Comment by mrDIMAS** [comment]
Good news - I got the engine working on Android: 

![image](https://user-images.githubusercontent.com/2785135/222232823-83e725d5-e0d3-4ede-a426-2d318be3c4ff.png)

However, there's no sound support yet - `fyrox-sound` needs a separate backend for Android. Also, the overall rendering performance is quite bad on middle-end devices because of very heavy PC-oriented renderer. I'm planning to write a separate, lightweight renderer for mobile devices.

**Comment by chriisduran** [comment]
Awesomeee, very awesome,  i hope Fyrox can increase in features!

**Comment by mrDIMAS** [comment]
Basic Android support was added. Use `fyrox-template` to generate a new project, it now contains `executor-android` which compiles your game for Android. 

I also created two new issues: new renderer for mobile devices - #434 and sound backend for Android - #435.
