### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#216]
The engine has become quite slow, especially the renderer. It should be profiled thorougly and optimized.

**Comment by mrDIMAS** [comment]
Concurrency is indeed possible, but only for physics, but afaik Rapier physics engine has built-in fork-join parallelism support, which makes manual offtreading of physics almost useless. 

`draw_recursively` cannot be source of performance issues in the editor only because it is "redefined each call", it just a local function, it just has smaller scope, thats it.

**Comment by mrDIMAS** [comment]
In the meantime there is already 2x performance boost 🎉 . I'm thoroughly going through hot paths that profiler shows and optimizing them (with various degree of success). For example `3rd_person` example was ~58-64 FPS before optimizations, now it is ~114-120 FPS. There is still lots possible optimizations that I want to do, for example - use uniform buffers, use octree for scene nodes to speed up culling (including culling in shadow mapping), and so on.

**Comment by zhneeshnek** [comment]
very cool.

yeah i realized local definition does not diminish performance, but i thought it still would be useful for the readability (still very readable as it is)

**Comment by w-flo** [comment]
I noticed a huge performance improvement in my toy project, too! Great work! I dropped most of my local changes because they actively made some things worse and didn't really help that much with performance compared to what you did. E.g. I previously changed the BatchStorage to only include meshes that are in the camera visibility cache, but that will break shadows and causes geometry to be uploaded to the GPU lazily, leading to freezes when lots of new geometry becomes visible.

I only have one remaining local change that really helps in my project because I don't use skeletal animations: Using a `Vec<Matrix4<f32>>` for bone matrices in the batch storage surface instance instead of `ArrayVec<Matrix4<f32>, 64>`. I guess the ArrayVec is collected from the iterator into a 0-length ArrayVec on the stack with 4K bytes as a buffer, and then moved into the batch storage on the heap through memmove or similar, which apparently adds up to a millisecond or two per frame for my project.

When collecting into a `Vec`, there should be no heap allocation for the 0 bones case and one heap allocation for every other case, but moving the Vec object from the stack into the struct should be fast because it's small. Anyway, this change reduced avg frame time in my benchmark from ~8ms to ~6ms in release mode. I'm not sure if this would kill performance for scenes with lots of meshes that use skeletal animation.
