### ISSUE TITLE
Wayland doesn't support exclusive fullscreen, but, it support fullscreen.

### ISSUE THREAD

**Issue by Eragonfr** [FyroxEngine/Fyrox#22]
When I start rusty-shooter, and go to the parameters, I can change the resolution of the game or pass it in fullscreen.
But if I do it, the game crash with this error message
```
thread 'main' panicked at 'Wayland doesn't support exclusive fullscreen', /home/eragon/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/linux/wayland/window.rs:342:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(I can run the game with `RUST_BACKTRACE=1` If you need more info)
Of course there is more lines after the panic, like `GL texture was destroyed`

I think it's not related to rusty-shooter but more to the implementation of wayland and fullscreen inside the engine.

PS: Sure X.org and Wayland is different, and there is a long way to go before having a good support of wayland. But I think If you(because… I don't think I'm not actually ready to help more than testing the engine and reporting bug) can fix these bugs(this one, and the one related to the mouse and the keyboard input) you can have a pretty good support of wayland.

Good luck, and thank you for your work on the engine, this is amazing !

**Comment by mrDIMAS** [comment]
Hi, the problem is that this panic comes from winit crate. I'm using glutin for OpenGL, and glutin is based on top of winit. So far all the problems related to Wayland in the engine actually related to winit crate. I had crazy idea before to throw away glutin and winit and write window and OpenGL initialization by myself, but then I realized I have more important stuff to do - like write engine and all stuff needed for it. I guess it is better to just use borderless fullscreen window, instead of exclusive fullscreen mode.
