### ISSUE TITLE
Add support for blend shapes/morph targets/shape keys

### ISSUE THREAD

**Issue by halbe** [FyroxEngine/Fyrox#223]
https://docs.blender.org/manual/en/latest/animation/shape_keys/introduction.html

Blend shapes are very useful for improving quality of animations, such as addressing scenarios that bone animation is very poor at like when a limb with a complex joint is stretched significantly, often around the hips and shoulders, as well as allow you to implement sliders for a character creator that do things other than just recolor or move bones around.

Here's an example from my base human mesh, I can morph it to be skinny, fat, muscular, male, or female with one base mesh. Morph targets can also utilize weighted vertex groups, so I could use the vertex groups for his arm bones to make him only muscular in the arms or any other combination that's desired.
![image](https://user-images.githubusercontent.com/26052993/140559776-a19f1ae8-c53e-403e-accb-b8f88d29b219.png)
![image](https://user-images.githubusercontent.com/26052993/140559860-d0089fe9-5656-4f7d-974c-220bf1e4e47f.png)

**Comment by echelon** [comment]
@mrDIMAS I'm not sure if there are bounties for tickets in Fyrox, but I'd be happy to pay for a blend shape implementation. This would be killer.

**Comment by mrDIMAS** [comment]
I'm currently working on overall animation system improvements, so it looks like this task fits nicely into my list. However, I need to finish animation/absm editors rework and check if they're working as intended. 

Also, I never done blend shapes, so it needs some research before trying to implement it. Afaik, it something similar to old school morph animations where you blend vertices between two pre-made meshes. 

@echelon As for payment, there's only one way that I can get money - boosty.to/fyrox (in case you missed - https://github.com/FyroxEngine/Fyrox/issues/363 , still waiting when the dictator die and things will start improving).

**Comment by mrDIMAS** [comment]
@echelon I saw your post on HN (https://news.ycombinator.com/item?id=35183284), we can discuss of what you need here. You need to have an ability to load (from fbx for instance) and combine multiple blend shapes?

**Comment by echelon** [comment]
@mrDIMAS I love the work you're doing here. You're a hero! I just subscribed to your highest tier, but I'd be happy to do more. 

We're building an AI chat bot in Unreal Engine and animating facial morph targets. We have 16 visemes and potentially thousands of vertices per model. (This depends on the character and the face.) 

We'd love to develop more capabilities around animation, but in the near term we just want to do facial morph target animation on Rust deployed as WASM to the browser targeting the upcoming WebGPU. We can calculate the animations server side, but we want to drive the animation itself on the client instead of "pixel streaming" video. Morph targets for face, bones for character body animation. 

Here's a very early prototype of what we're doing: 

https://m.twitch.tv/videos/1746464254

We've got much more in the background we're going to release soon. We're developing this to do music, narrative, storytelling, etc. 

We'd love to ditch Unreal Engine and go 100% Rust for everything. Our ML stack and web API services are tch-rs and Actix. Our entire company is rooted in the Rust ecosystem. We'd love to skip Godot on the browser and go directly with Fyrox. 

I know this will take time, and our timeline affords us the ability to keep delivering on Unreal Engine as Rust continues to mature. I'd love to have an offline / email / Discord chat about your roadmap and what we can do to sponsor it. 

My personal email is [my username] @ gmail.com, and my Discord is echelon#0001. 

Keep it up with Fyrox! I'm excited every time your release headlines are on HN and /r/rust.

**Comment by mrDIMAS** [comment]
Thank you for the kind words and support, I really appreciate this! 

Basic blend shape support will require at least two steps:

1) CPU vertex blending between multiple shapes into one. CPU blending can then be replaced with GPU blending, that will require some further research. It seems that the most viable solution for Web is to use transform feedback feature of OpenGL ES. I think that with the given "vertex budget" (as you writing - thousands of vertices) it can be easily done on CPU and while there's only a handful of such 3d models with blend shapes on screen, pretty much any (even low-end) device can handle this. I estimate this step as a week of work at max.
2) Add support for Morph deformers in FBX importer to be able to load faces 3D models with blend shapes. This step could be problematic, since it will require some reverse-engineering of FBX format. I estimate this step as a week of work too.

**Comment by mrDIMAS** [comment]
Turned out that this was quite easy to implement and I managed to add basic blend shapes support in just two days. See #440 for examples.
