### ISSUE TITLE
Editor high CPU usage

### ISSUE THREAD

**Issue by hw762** [FyroxEngine/Fyrox#360]
It seems that the Fyrox editor eats 100% cpu (one core) even at idle. Is something spinning a loop? It would be nice if this usage can be reduced.

**Comment by martin-t** [comment]
Make sure you've compiled the editor in release mode.

Apart from that I am also noticing 100% CPU usage in my game, seems to only happen after it's been left minimized for a while.

**Comment by vpochapuis** [comment]
I have experienced a similar CPU Usage issue.
Issue to reproduce:

- Start the Editor in Release mode
- Click `Play` in the editor
- Do not quit the game using the game window, but the Editor's "Stop" button

Result:
CPU percentage usage increases.

I can repeat this indefinitely until my total CPU load is 100%.

One of the weird aspect of this issue, the CPU usage increase doesn't happen when the game is started, it happens when the game is closed.

Here is the CPU usage during the following procedure:
- Start and stop the game from the editor several times
- Close the editor

![image](https://user-images.githubusercontent.com/75721408/208374158-489a1a83-dfe6-4d21-83f6-fd1ee450ff15.png)

**Comment by mrDIMAS** [comment]
Interesting bug, it is definitely should be fixed asap. Thanks for the report.

**Comment by lvella** [comment]
I just opened the editor and it stood there, doing nothing but consuming 50% of the CPU. Same thing both in release and debug mode.

**Comment by mrDIMAS** [comment]
Fixed in #520.
