### ISSUE TITLE
Enable sponsoring in GitHub

### ISSUE THREAD

**Issue by vcrn** [FyroxEngine/Fyrox#363]
I don't know if there would be any downsides using GitHub in addition/in stead of Patreon, but I think it would be a good idea to add the ability to sponsor the project via one's GitHub account. I believe the threshold for new sponsors would be lower since they are guaranteed to already have a GitHub account, which isn't the case regarding Patreon.

**Comment by mrDIMAS** [comment]
Hi! Just so you know - I'm from Russia, many companies left Russia recently. GitHub Sponsor wasn't even available before that, money on Patreon are somewhat blocked too - Paypay does not work in Russia. The only way for me getting money for development is to use other platforms that works in Russia. Recently I made an account in Boosty - https://boosty.to/fyrox 

Sooo... I'm somewhat isolated from civilized world and getting funding is _very hard_ in this situation. I didn't get a cent since February, it is all split between Patreon and Paypal accounts. I hope someday my country will be friendly to other countries, it is sad to see what's happening currently.

**Comment by vcrn** [comment]
I'm sorry to hear that! Hopefully things will get better soon. I'll check out the link and see if I can change my sponsorship from Patreon to that one.

**Comment by git2013vb** [comment]
>  I didn't get a cent since February, it is all split between Patreon and Paypal accounts. I hope someday my country will be friendly to other countries, it is sad to see what's happening currently.

Yeah. I know lots of Russian people - like yourself ocf :) -  are against the war,  But the situation cannot be resolved just hoping for the best. Russian people have to do more. The risk of a ww3 is high. I don't say you personally  but in general people need to wake up.  We (as human being)  cannot afford a global scale war. You know,.. what the point to have a good game engine in a post apocalyptical world? :)

**Comment by ReDev1L** [comment]
@mrDIMAS 
`https://coindrop.to/`
Make this one, then you will be able to get cash through Binance
