### ISSUE TITLE
request_sound_buffer: condvar wait not supported

### ISSUE THREAD

**Issue by GOVYANSONG** [FyroxEngine/Fyrox#406]
I run into this issue with sound manager. code snippet:

resource_manager
                .as_ref()
                .unwrap()
                .request_sound_buffer(path.as_ref())

Just want to confirm that it is not caused by block_on etc. in the codebase.

**Comment by mrDIMAS** [comment]
This is weird, is `wasm` example works for you? It should play music and it is played from a file that is request by the same code snippet as you provided.

**Comment by GOVYANSONG** [comment]
I will investigate more on my end. during meantime, just to record more details about the error:

Attempt to get reference to resource data while it is not loaded! Path is data/sounds/step.wav

Parking not supported on this platform', /home/mk8s/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.4/src/thread_parker/wasm.rs:26

**Comment by mrDIMAS** [comment]
Aha, you need to wait until the sound is fully loaded, every resource in the engine implements `Future` trait so it can be put into an async executor. Not sure what's the best way to do this since you cannot block current thread while waiting future result on wasm. It might be worth to create a simple sound manager that will take path to a sound, request it from the resource manager, spawn a task that will put loaded resources in to a queue. Then extract loaded sounds from the queue and play them.

Ideally, you shoudn't request any resources from scripts. You can just add a `sound: Option<SoundBuffer>` field to your script and then drag'n'drop a sound from Asset Browser on that field in the Inspector. This way the engine will handle resources for you.

**Comment by mrDIMAS** [comment]
I managed to reproduce the issue, I'll try to fix it today.

**Comment by mrDIMAS** [comment]
Alright, it is not an actual issue, it is just quirks of resource management of the engine. When you store a `sound: Option<SoundBufferResource>` in your script, the engine will save only path the resource on serialization step (when you save the scene in the editor). To restore actual resource from its "shallow" version you need to add this code in `restore_resources` method of your script:

```rust
resource_manager
            .state()
            .containers_mut()
            .sound_buffers
            .try_restore_optional_resource(&mut self.sound);
```

This is well known issue, and in future versions this method will be replaced with reflection-based solution so you don't need to re-fetch resources anymore.

**Comment by mrDIMAS** [comment]
I also fixed some other issues that I spotted along the way: missing property editor for sound status in Sound node, and wrong sync order of sound properties.

**Comment by GOVYANSONG** [comment]
Never mind, i misunderstood the line for restore_resources method. will verify now.

**Comment by GOVYANSONG** [comment]
@mrDIMAS the sound is now working as expected. thanks for the superb assistance.
